CREATE TABLE CITY
(
    id BIGINT generated by default as identity,
    name VARCHAR(255) UNIQUE NOT NULL ,
    created TIMESTAMP,
    status VARCHAR(255),
    updated TIMESTAMP,
    primary key (id)
);






