CREATE TABLE EVENT
(
    id BIGINT generated by default as identity,
    date VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    max_members INT NOT NULL,
    description VARCHAR(2048) NOT NULL,
    city_id BIGINT NOT NULL,
    holder_id BIGINT NOT NULL,
    created TIMESTAMP,
    status VARCHAR(255),
    updated TIMESTAMP,
    primary key (id)
);
