CREATE TABLE USER
(
    id BIGINT generated by default as identity,
    email VARCHAR(255) ,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    username VARCHAR(255) UNIQUE NOT NULL,
    wants_new_role BOOLEAN,
    created TIMESTAMP,
    status VARCHAR(255),
    updated TIMESTAMP,
    primary key (id)
);
