CREATE TABLE EVENT
(
    id BIGINT generated by default as identity,
    date VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    max_members INT NOT NULL,
    name VARCHAR(255),
    city_id BIGINT NOT NULL,
    primary key (id)
);
